### PR TITLE
java sorting algorithms

### PR DESCRIPTION
**Pull request by bhaviya18**
I have added a new folder named java-sorting within which i have added both binary and linear search
fixed issue #123

### CODE REVIEW

**Comment by chetannihith** [comment]
Let me know if you PR is valid or getting excluded in hacktoberfest.....Thank You

**Comment by bhaviya18** [comment]
@chetannihith My pr is being excluded on the website

**Comment by chetannihith** [comment]
I am unable to open the screenshot...Can you send that one in another way

**Comment by chetannihith** [comment]
Also. I don't know somehow but this time they have made hacktoberfest more strict than last year......
It is advisable to avoid DSA related or low priority PRs.
Thank you

**Comment by bhaviya18** [comment]
Ok thank you

**Pull request merged**
