### PR TITLE
Create BinarySearch.java

### PR DESCRIPTION
**Pull request by abhi07aryan**

### CODE REVIEW

**Comment by abhi07aryan** [comment]
This program searches an element in an integer array by using Binary Search algorithm.

**Comment by abhi07aryan** [comment]
Why did you not merge this one?

**Comment by chetannihith** [comment]
@abhi07aryan I saw this binary search pr repeated in the past and have closed all of them.

**Comment by abhi07aryan** [comment]
What should I make next?

**Comment by chetannihith** [comment]
Make pr on leet code questions or something that is unique!

**Pull request closed without merging**
