### PR TITLE
this is the code related to packages

### PR DESCRIPTION
**Pull request by VETREA**
please check this code and reply to it

### CODE REVIEW

**Comment by chetannihith** [comment]
You forgot to include package.java!

**Comment by VETREA** [comment]
> You forgot to include package.java!

@chetannihith can you tell me where i missed it ?

**Comment by chetannihith** [comment]
there are no contents shown in the file named package.java in the mypackage folder

**Review by VETREA — COMMENTED** [review]
now plz check it
@chetannihith

**Pull request closed without merging**
